import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { FiGithub } from 'react-icons/fi';
import { FiExternalLink } from 'react-icons/fi';
import country from './countries.jpg';
import Boktel from './Boktel.png';
import Fitness from './fit.png';
import emailjs from 'emailjs-com';
import { useRef, useState } from 'react';
import Swal from 'sweetalert2';

export default function Home() {
	const [darkMode, setDarkMode] = useState(true);
	const [side, setSide] = useState(false);
	const [active, setActive] = useState('');
	const SERVICE_ID = 'service_lf3s3cx';
	const TEMPLATE_ID = 'template_rif9cbv';
	const USER_ID = 'EA7O3nm5B95-3f8SA';
	const [scroll, setScroll] = useState(false);

	const handleNav = (e) => {
		const name = e.target.getAttribute('name');

		if (name === 'about') {
			setActive('about');
			window.scrollTo({
				bottom: 0,
				top: 640,
				behavior: 'smooth',
			});
		} else if (name === 'work') {
			setActive('work');
			window.scrollTo({
				bottom: 0,
				top: 1110,
				behavior: 'smooth',
			});
		} else if (name === 'contact') {
			setActive('contact');
			window.scrollTo({
				bottom: 0,
				top: 4870,
				behavior: 'smooth',
			});
		}
	};

	const handleAbout = async (e) => {
		console.log(e.target.getAttribute('name'));

		const name = e.target.getAttribute('name');

		await setSide((prev) => !prev);

		if (name === 'about') {
			window.scrollTo({
				bottom: 0,
				top: 440,
				behavior: 'smooth',
			});
		} else if (name === 'work') {
			window.scrollTo({
				bottom: 0,
				top: 980,
				behavior: 'smooth',
			});
		} else if (name === 'contact') {
			window.scrollTo({
				bottom: 0,
				top: 4300,
				behavior: 'smooth',
			});
		}
	};

	const changeClass = () => {
		const scrollValue =
			document.body.scrollTop || document.documentElement.scrollTop;

		if (scrollValue > 100) {
			setScroll(true);
		} else {
			setScroll(false);
		}
	};
	window.addEventListener('scroll', changeClass);

	const handleSubmit = (e) => {
		e.preventDefault();

		emailjs.sendForm(SERVICE_ID, TEMPLATE_ID, e.target, USER_ID).then(
			(result) => {
				console.log(result.text);
				Swal.fire({
					icon: 'success',
					title: 'Message Sent Successfully',
				});
			},
			(error) => {
				console.log(error.text);
				Swal.fire({
					icon: 'error',
					title: 'Ooops, something went wrong',
					text: error.text,
				});
			}
		);
		e.target.reset();
	};

	return (
		<div className={darkMode ? 'bg-gray-800' : 'bg-gray-300'}>
			<div className=' '>
				<title>Youssef Albokl</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='stylesheet'
					href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
				/>
				<link rel='icon' href='/favicon.ico' />
			</div>

			<main className={'  px-10 md:px-20 lg:px-40 '}>
				<div>
					{side && (
						<div
							className={
								'w-screen h-screen opacity-90 z-10 -ml-10 ' +
								(darkMode ? 'bg-gray-800' : 'bg-gray-400')
							}
						>
							<div
								className=' p-10'
								onClick={() => setSide((prev) => !prev)}
							>
								{' '}
								<svg
									xmlns='http://www.w3.org/2000/svg'
									fill='none'
									color={darkMode ? 'white' : 'black'}
									viewBox='0 0 24 24'
									strokeWidth={1.8}
									stroke='currentColor'
									className='w-8 h-8 ml-auto'
								>
									<path
										strokeLinecap='round'
										strokeLinejoin='round'
										d='M6 18L18 6M6 6l12 12'
									/>
								</svg>
							</div>
							<div className=' '>
								<ul className='  flex-column p-16 ml-24'>
									<li
										onClick={(e) => handleAbout(e)}
										name='about'
										className={
											' text-3xl cursor-pointer  font-semibold font-mono hover:text-teal-500 ' +
											(darkMode
												? 'text-gray-200'
												: 'text-gray-900')
										}
									>
										<span className=' text-teal-500 text-3xl font-semibold font-mono'>
											01.
										</span>{' '}
										About
									</li>{' '}
									<li
										onClick={(e) => handleAbout(e)}
										name='work'
										className={
											' text-3xl cursor-pointer mt-6 lg:hidden  text-gray-200 mr-2 font-semibold font-mono hover:text-teal-500 ' +
											(darkMode
												? 'text-gray-300'
												: 'text-gray-900')
										}
									>
										<span className=' text-teal-500 text-3xl font-semibold font-mono '>
											02.
										</span>{' '}
										Projects
									</li>
									<li
										onClick={(e) => handleAbout(e)}
										name='contact'
										className={
											' text-3xl cursor-pointer mt-6 text-gray-200 mr-2 font-semibold font-mono hover:text-teal-500 ' +
											(darkMode
												? 'text-gray-300'
												: 'text-gray-900')
										}
									>
										<span className=' text-teal-500 text-3xl font-semibold font-mono '>
											03.
										</span>{' '}
										Contact
									</li>
									<li className='hover:scale-105 mt-14'>
										<a
											className={
												' text-xl  bg-gradient-to-r  border px-10 py-2  rounded-md ml-2 transition-all hover:bg-teal-500   ' +
												(darkMode
													? 'text-slate-100   border-teal-500 bg-gray-800'
													: 'text-gray-800 hover:text-gray-200 border-teal-500 bg-gray-300 ')
											}
											href='https://drive.google.com/file/d/1gOTd1_JtISAQgULCUnCfryDxCiWsVCaO/view?usp=share_link'
											target='_blank'
										>
											Resume
										</a>
									</li>
								</ul>
							</div>
						</div>
					)}
					{!side && (
						<div>
							{' '}
							<section className='pb-3 lg:pb-40 '>
								<div className=' '>
									<div
										className={
											'lg:hidden fixed -mr-8 -ml-8   right-8 left-10 justify-between flex px-4 py-4  ' +
											(scroll
												? (darkMode
														? 'bg-gray-800 '
														: 'bg-gray-300 ') +
												  ' shadow-lg opacity-90  '
												: ' py-4')
										}
									>
										<h1
											className={
												' text-3xl italic font-burton font-semibold   hover:text-teal-500 ' +
												(darkMode
													? 'text-slate-300'
													: '')
											}
										>
											Bokl
										</h1>
										<div className='mt-1 ml-auto flex gap-3'>
											{darkMode && (
												<svg
													onClick={() =>
														setDarkMode(!darkMode)
													}
													className={
														'cursor-pointer mt-1 text-xl md:transition-all hover:fill-yellow-300  md:hover:scale-125 w-6 h-6  ' +
														(darkMode
															? 'text-white'
															: '')
													}
													xmlns='http://www.w3.org/2000/svg'
													viewBox='0 0 24 24'
													fill={'white'}
												>
													<path d='M12 2.25a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0V3a.75.75 0 01.75-.75zM7.5 12a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM18.894 6.166a.75.75 0 00-1.06-1.06l-1.591 1.59a.75.75 0 101.06 1.061l1.591-1.59zM21.75 12a.75.75 0 01-.75.75h-2.25a.75.75 0 010-1.5H21a.75.75 0 01.75.75zM17.834 18.894a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 10-1.061 1.06l1.59 1.591zM12 18a.75.75 0 01.75.75V21a.75.75 0 01-1.5 0v-2.25A.75.75 0 0112 18zM7.758 17.303a.75.75 0 00-1.061-1.06l-1.591 1.59a.75.75 0 001.06 1.061l1.591-1.59zM6 12a.75.75 0 01-.75.75H3a.75.75 0 010-1.5h2.25A.75.75 0 016 12zM6.697 7.757a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 00-1.061 1.06l1.59 1.591z' />
												</svg>
											)}
											{!darkMode && (
												<svg
													onClick={() =>
														setDarkMode(!darkMode)
													}
													className={
														'cursor-pointer mt-1 text-xl md:transition-all hover:fill-gray-800 md:hover:scale-125 w-6 h-6  ' +
														(darkMode
															? 'text-white'
															: '')
													}
													xmlns='http://www.w3.org/2000/svg'
													viewBox='0 0 24 24'
													fill='black'
												>
													<path
														fillRule='evenodd'
														d='M9.528 1.718a.75.75 0 01.162.819A8.97 8.97 0 009 6a9 9 0 009 9 8.97 8.97 0 003.463-.69.75.75 0 01.981.98 10.503 10.503 0 01-9.694 6.46c-5.799 0-10.5-4.701-10.5-10.5 0-4.368 2.667-8.112 6.46-9.694a.75.75 0 01.818.162z'
														clipRule='evenodd'
													/>
												</svg>
											)}

											<svg
												onClick={() =>
													setSide((prev) => !prev)
												}
												xmlns='http://www.w3.org/2000/svg'
												fill='white'
												color={
													darkMode ? 'white' : 'black'
												}
												viewBox='0 0 22 22'
												strokeWidth={1.5}
												stroke='currentColor'
												className='w-8 h-8 '
											>
												<path
													strokeLinecap='round'
													strokeLinejoin='round'
													d='M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5'
												/>
											</svg>
										</div>
									</div>
									<nav
										className={
											'hidden lg:flex  -ml-40 -mr-40 px-40  mb-12 fixed  right-12 left-24 justify-between ' +
											(scroll
												? (darkMode
														? 'bg-gray-800 '
														: 'bg-gray-300 ') +
												  ' shadow-lg opacity-90 py-4 '
												: ' py-8')
										}
									>
										<h1
											className={
												' text-lg italic font-burton font-semibold md:text-2xl  hover:text-teal-500 ' +
												(darkMode
													? 'text-slate-300'
													: '')
											}
										>
											Bokl
										</h1>
										<ul className='flex items-center gap-3'>
											<li
												name='about'
												className={
													' text-sm cursor-pointer  mr-2 font-semibold font-mono hover:text-teal-500 ' +
													(darkMode
														? 'text-gray-200'
														: 'text-gray-900') +
													(active === 'about'
														? ' text-teal-500'
														: '')
												}
												onClick={(e) => handleNav(e)}
											>
												<span className=' text-teal-500 font-semibold font-mono'>
													01.
												</span>{' '}
												About
											</li>

											<li
												name='work'
												className={
													' text-sm cursor-pointer hidden lg:block  text-gray-200 mr-2 font-semibold font-mono hover:text-teal-500 ' +
													(darkMode
														? 'text-gray-300'
														: 'text-gray-900') +
													(active === 'work'
														? ' text-teal-500'
														: ' ')
												}
												onClick={(e) => handleNav(e)}
											>
												<span className=' text-teal-500 font-semibold font-mono '>
													02.
												</span>{' '}
												Projects
											</li>

											<li
												name='contact'
												className={
													' text-sm cursor-pointer text-gray-200 mr-2 font-semibold font-mono hover:text-teal-500 ' +
													(darkMode
														? 'text-gray-300'
														: 'text-gray-900') +
													(active === 'contact'
														? ' text-teal-500'
														: ' ')
												}
												onClick={(e) => handleNav(e)}
											>
												<span className=' text-teal-500 font-semibold font-mono '>
													03.
												</span>{' '}
												Contact
											</li>
											<li>
												{darkMode && (
													<svg
														onClick={() =>
															setDarkMode(
																!darkMode
															)
														}
														className={
															'cursor-pointer text-xl md:transition-all hover:fill-yellow-300  md:hover:scale-125 w-6 h-6  ' +
															(darkMode
																? 'text-white'
																: '')
														}
														xmlns='http://www.w3.org/2000/svg'
														viewBox='0 0 24 24'
														fill={'white'}
													>
														<path d='M12 2.25a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0V3a.75.75 0 01.75-.75zM7.5 12a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM18.894 6.166a.75.75 0 00-1.06-1.06l-1.591 1.59a.75.75 0 101.06 1.061l1.591-1.59zM21.75 12a.75.75 0 01-.75.75h-2.25a.75.75 0 010-1.5H21a.75.75 0 01.75.75zM17.834 18.894a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 10-1.061 1.06l1.59 1.591zM12 18a.75.75 0 01.75.75V21a.75.75 0 01-1.5 0v-2.25A.75.75 0 0112 18zM7.758 17.303a.75.75 0 00-1.061-1.06l-1.591 1.59a.75.75 0 001.06 1.061l1.591-1.59zM6 12a.75.75 0 01-.75.75H3a.75.75 0 010-1.5h2.25A.75.75 0 016 12zM6.697 7.757a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 00-1.061 1.06l1.59 1.591z' />
													</svg>
												)}
												{!darkMode && (
													<svg
														onClick={() =>
															setDarkMode(
																!darkMode
															)
														}
														className={
															'cursor-pointer text-xl md:transition-all hover:fill-gray-800 md:hover:scale-125 w-6 h-6  ' +
															(darkMode
																? 'text-white'
																: '')
														}
														xmlns='http://www.w3.org/2000/svg'
														viewBox='0 0 24 24'
														fill='black'
													>
														<path
															fillRule='evenodd'
															d='M9.528 1.718a.75.75 0 01.162.819A8.97 8.97 0 009 6a9 9 0 009 9 8.97 8.97 0 003.463-.69.75.75 0 01.981.98 10.503 10.503 0 01-9.694 6.46c-5.799 0-10.5-4.701-10.5-10.5 0-4.368 2.667-8.112 6.46-9.694a.75.75 0 01.818.162z'
															clipRule='evenodd'
														/>
													</svg>
												)}
											</li>
											<li className='hover:scale-105'>
												<a
													className={
														' text-md  bg-gradient-to-r  border px-3 py-2  rounded-md ml-2 transition-all hover:bg-teal-500   ' +
														(darkMode
															? 'text-slate-100   border-teal-500 bg-gray-800'
															: 'text-gray-800 hover:text-gray-200 border-teal-500 bg-gray-300 ')
													}
													href='https://drive.google.com/file/d/1gOTd1_JtISAQgULCUnCfryDxCiWsVCaO/view?usp=share_link'
													target='_blank'
												>
													Resume
												</a>
											</li>
										</ul>
									</nav>
								</div>
							</section>
							<section>
								<div className=' text-center p-10 mt-14 '>
									<h2 className=' text-3xl  font-bold text-teal-500 py-2 md:text-6xl writer writer-text'>
										Hi, I'm Youssef Albokl.
									</h2>
									<h3
										className={
											' text-lg py-2 md:text-3xl ' +
											(darkMode ? 'text-slate-300' : '')
										}
									>
										A Full-stack developer.
									</h3>
									<p
										className={
											' text-base py-4 leading-6 md:text-xl max-w-xl mx-auto ' +
											(darkMode
												? 'text-slate-400'
												: ' text-gray-700')
										}
									>
										Impassioned Full-stack developer based
										in Cairo, Egypt with an emphasis on
										responsive design.
									</p>
								</div>
								<div
									className={
										'flex justify-center gap-16 text-5xl py-3   ' +
										(darkMode
											? 'text-slate-200'
											: 'text-gray-700')
									}
								>
									<a
										className='transition-all hover:scale-125'
										href='https://www.linkedin.com/in/youssefalbokl/'
										target='_blank'
									>
										{' '}
										<AiFillLinkedin />{' '}
									</a>
									<a
										className='transition-all hover:scale-125'
										href='https://github.com/Boklino'
										target='_blank'
									>
										<AiFillGithub />{' '}
									</a>
								</div>
								<div className=' mb-30'>
									<h1
										className={
											' font-burtons text-3xl mt-32 ' +
											(darkMode ? 'text-slate-300' : '')
										}
									>
										About me
									</h1>
									<p
										className={
											' font-burtons text-xl mt-8 ' +
											(darkMode ? 'text-slate-300' : '')
										}
									>
										I am a{' '}
										<span className=' text-teal-600'>
											Full-stack{' '}
										</span>
										developer with knowledge in many
										different front end and back end
										languages, responsive frameworks,
										databases, and best code practices. I
										specialize in{' '}
										<span className=' text-teal-600'>
											MERN
										</span>{' '}
										stack. My goal is to create responsive
										designs and keep myself updated with
										recent technologies in the field, I also
										believe that I have to keep learning new
										ideas everyday.
									</p>
									<p
										className={
											' font-burtons text-xl mt-8 ' +
											(darkMode ? 'text-slate-300' : '')
										}
									>
										Here are a few technologies I’ve been
										working with recently:
									</p>
									<ul
										className={
											' font-burtons list-image-[url(checkmark.png)] text-md mt-8 grid grid-cols-2 list-inside  ' +
											(darkMode ? 'text-slate-300' : '')
										}
									>
										<li className='flex gap-1'>
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											JavaScript (ES6+)
										</li>

										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											React Native
										</li>

										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>{' '}
											React
										</li>
										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											TypeScript
										</li>
										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											Node.js
										</li>
										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											Tailwind
										</li>
										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											MongoDB
										</li>
										<li className='flex gap-1'>
											{' '}
											<svg
												xmlns='http://www.w3.org/2000/svg'
												viewBox='0 0 24 24'
												fill='currentColor'
												className='w-5 h-5 mt-1'
											>
												<path
													fillRule='evenodd'
													d='M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z'
													clipRule='evenodd'
												/>
											</svg>
											Sass
										</li>
									</ul>
								</div>
							</section>
							<section
								className={darkMode ? ' bg-gray-800' : ' '}
							>
								<div>
									<h1
										className={
											' font-burtons text-3xl mt-32 ' +
											(darkMode ? 'text-slate-300 ' : '')
										}
									>
										Personal Projects
									</h1>
									<div className=' mt-4 '>
										{' '}
										<p
											className={
												'text-sm ' +
												(darkMode
													? 'text-slate-300'
													: '')
											}
										>
											Featured Project
										</p>
										<a
											href='https://boktel.vercel.app/'
											target='_blank'
										>
											<h2 className=' mt-3 text-2xl text-teal-600'>
												Boktel
											</h2>
										</a>
										<div
											className={
												'-mt-20 lg:-mt-0  lg:absolute -ml-48 lg:-ml-40 p-40  lg:w-full lg:h-full ' +
												(darkMode
													? 'bg-gray-800'
													: 'bg-gray-300')
											}
										>
											<div className='lg:relative lg:left-80 lg:bottom-28 absolute '>
												<a
													href='https://boktel.vercel.app/'
													target='_blank'
												>
													{' '}
													<img
														className='transition transform hover:opacity-80 hover:shadow-slate-500 lg:w-8/12 '
														src={Boktel}
													/>
												</a>
											</div>
											<div
												className={
													'  p-5  lg:w-4/12 lg:left-20 items-center  py-12 lg:py-5 lg:opacity-90 opacity-75 lg:top-20 z-10 lg:rounded-lg absolute lg:absolute  ' +
													(darkMode
														? 'bg-slate-800 shadow-lg opacity-80 '
														: 'bg-gray-300 shadow-lg opacity-90')
												}
											>
												<p
													className={
														darkMode
															? 'text-white lg:text-gray-300'
															: 'text-black lg:text-gray-800'
													}
												>
													Experience the essence of
													travel with Boktel, a
													dynamic platform that
													combines the best of Airbnb
													and hotel booking. Whether
													you're a wanderlust seeker
													or a property owner looking
													to share your unique spaces,
													Boktel connects you with a
													world of possibilities.
													<div
														className={
															' flex gap-3 mt-3 absolute opacity-90 lg:hidden   ' +
															(darkMode
																? 'text-gray-200 lg:text-gray-300'
																: 'text-black')
														}
													>
														<p>React </p>
														<p>Node.js</p>
														<p>MongoDB</p>
														<p>React Router</p>
														<p>Tailwind</p>
													</div>
													<div className='flex lg:hidden mt-16 gap-4 lg:absolute opacity-75 '>
														<a
															href='https://github.com/Boklino/boktel'
															target='_blank'
														>
															{' '}
															<FiGithub
																size={22}
																color={
																	darkMode
																		? 'white'
																		: 'black'
																}
															/>
														</a>

														<FiExternalLink
															size={22}
															color={
																darkMode
																	? 'white'
																	: 'black'
															}
														/>
													</div>
												</p>
											</div>
											<div className=' lg:absolute p-5 lg:left-16 ml-2 lg:bottom-96 lg:top-60'>
												<div
													className={
														' lg:flex gap-3 hidden ' +
														(darkMode
															? 'text-gray-200 lg:text-gray-300'
															: 'text-black')
													}
												>
													<p>React </p>
													<p>Node.js</p>
													<p>MongoDB</p>
													<p>React Router</p>
													<p>Tailwind</p>
												</div>
											</div>
											<div className='flex gap-4 lg:absolute p-5 left-52 bottom-72 top-72'>
												<a
													href='https://github.com/Boklino/boktel'
													target='_blank'
												>
													{' '}
													<FiGithub
														size={22}
														color={
															darkMode
																? 'white'
																: 'black'
														}
													/>
												</a>
												<a
													href='https://boktel.vercel.app/'
													target='_blank'
												>
													{' '}
													<FiExternalLink
														size={22}
														color={
															darkMode
																? 'white'
																: 'black'
														}
													/>
												</a>
											</div>
										</div>
									</div>
									<div className=' mt-1 lg:mt-80 xl:mt-96  py-36 xl:py-96 '>
										<div className=' mt-24'>
											<p
												className={
													'text-sm mt-48 mb-3  ' +
													(darkMode
														? 'text-slate-300'
														: '')
												}
											>
												Featured Project
											</p>
											<h2 className=' text-2xl text-teal-600'>
												<a
													href='https://fitness-buddy1.netlify.app/'
													target='_blank'
												>
													Fitness Buddy
												</a>
											</h2>
										</div>

										<div
											className={
												'-mt-20 lg:-mt-0  lg:absolute -ml-48 lg:-ml-40 p-40  lg:w-full lg:h-full ' +
												(darkMode
													? 'bg-gray-800'
													: 'bg-gray-300')
											}
										>
											<div className='lg:relative lg:left-80 lg:bottom-28 absolute '>
												<a
													href='https://fitness-buddy1.netlify.app/'
													target='_blank'
												>
													<img
														className='transition transform hover:opacity-80 hover:shadow-slate-500 lg:w-8/12 mt-1 lg:mt-0 rounded-md shadow-lg '
														src={Fitness}
													/>
												</a>
											</div>
											<div
												className={
													'  p-5 lg:w-4/12 lg:left-20 items-center  py-12 lg:py-5 lg:opacity-90 opacity-80 lg:top-20 z-10 lg:rounded-lg absolute lg:absolute  ' +
													(darkMode
														? 'bg-slate-800 shadow-lg opacity-80'
														: 'bg-gray-300 shadow-lg opacity-90')
												}
											>
												<p
													className={
														darkMode
															? 'text-white lg:text-gray-300'
															: 'text-black lg:text-gray-800'
													}
												>
													Unleash your inner fitness
													enthusiast and achieve your
													wellness goals with
													FitnessBuddy. This
													innovative platform empowers
													you to craft your
													personalized workout
													routines from a vast library
													of exercises, accompanied by
													captivating GIFs and
													detailed explanations.
													<div
														className={
															'  p-5 lg:hidden  lg:w-4/12 lg:left-20 items-center  py-12 lg:py-5 lg:opacity-90 opacity-75 lg:top-20 z-10 lg:rounded-lg absolute lg:absolute  ' +
															(darkMode
																? 'bg-slate-800 shadow-lg'
																: 'bg-gray-400 shadow-lg')
														}
													>
														<div
															className={
																' flex gap-3 mt-3 absolute bottom-14 left-1 whitespace-nowrap  lg:hidden   ' +
																(darkMode
																	? 'text-gray-200 lg:text-gray-300'
																	: 'text-black')
															}
														>
															<p>React </p>
															<p>React-Router</p>
															<p>Tailwind</p>
															<p>Material-UI</p>
														</div>
													</div>
													<div className='flex lg:hidden mt-16 gap-3 ml-10 lg:absolute opacity-90 '>
														<a
															href='https://github.com/Boklino/gym-exercises'
															target='_blank'
														>
															<FiGithub
																size={22}
																color={
																	darkMode
																		? 'white'
																		: 'black'
																}
															/>
														</a>

														<a
															href='https://fitness-buddy1.netlify.app/'
															target='_blank'
														>
															<FiExternalLink
																size={22}
																color={
																	darkMode
																		? 'white'
																		: 'black'
																}
															/>
														</a>
													</div>
												</p>
											</div>
											<div className=' absolute p-5  left-14 ml-10 bottom-96 top-60'>
												<div
													className={
														' gap-3 mt-3 opacity-90 hidden lg:flex   ' +
														(darkMode
															? 'text-gray-200 lg:text-gray-300'
															: 'text-black')
													}
												>
													<p>React</p>
													<p>React Router</p>
													<p>Tailwind</p>
													<p>Material UI</p>
												</div>
											</div>
											<div className='hidden lg:flex gap-4 mt-2 absolute p-5 left-52 bottom-72 top-72'>
												<a
													href='https://github.com/Boklino/gym-exercises'
													target='_blank'
												>
													<FiGithub
														size={22}
														color={
															darkMode
																? 'white'
																: 'black'
														}
													/>
												</a>

												<a
													href='https://fitness-buddy1.netlify.app/'
													target='_blank'
												>
													<FiExternalLink
														size={22}
														color={
															darkMode
																? 'white'
																: 'black'
														}
													/>
												</a>
											</div>
										</div>
									</div>
								</div>
								<div className=' mt-1 lg:mt-64 xl:mt-96 py-36 '>
									<div className=' mt-24'>
										<p
											className={
												'text-sm mt-32 mb-3  ' +
												(darkMode
													? 'text-slate-300'
													: '')
											}
										>
											Featured Project
										</p>
										<a
											target='_blank'
											href='https://api-countriess.netlify.app/'
										>
											<h2 className=' text-2xl text-teal-600'>
												Countries Information
											</h2>
										</a>
									</div>

									<div
										className={
											'-mt-20 lg:-mt-0  lg:absolute -ml-48 lg:-ml-40 p-40  lg:w-full lg:h-full ' +
											(darkMode
												? 'bg-gray-800'
												: 'bg-gray-300')
										}
									>
										<div className='lg:relative lg:left-80 lg:bottom-28 absolute '>
											<a
												target='_blank'
												href='https://api-countriess.netlify.app/'
											>
												<img
													className=' hover:opacity-80 hover:shadow-slate-500 transition transform mt-1 lg:mt-0 lg:w-8/12 rounded-md shadow-lg '
													src={country}
												/>
											</a>
										</div>
										<div
											className={
												'  p-5  lg:w-4/12 lg:left-20 items-center  py-12 lg:py-5 lg:opacity-90 opacity-80 lg:top-20 z-10 lg:rounded-lg absolute lg:absolute  ' +
												(darkMode
													? 'bg-slate-800 shadow-lg opacity-80'
													: 'bg-gray-300 shadow-lg opacity-90')
											}
										>
											<p
												className={
													darkMode
														? 'text-white lg:text-gray-300'
														: 'text-black lg:text-gray-800'
												}
											>
												Embark on an immersive journey
												through the vast tapestry of our
												world's countries with
												WikiCounties. This comprehensive
												repository of information
												provides a captivating
												exploration of cultures,
												histories, and captivating facts
												about every nation on Earth.
												<div className='lg:hidden mt-28 mr-10 absolute p-5  '>
													<div
														className={
															' flex gap-3 absolute bottom-28   whitespace-nowrap  lg:hidden   ' +
															(darkMode
																? 'text-gray-200 lg:text-gray-300'
																: 'text-black')
														}
													>
														<p>React </p>
														<p>React Router</p>
														<p>Tailwind</p>
														<p>Material UI</p>
														<p>Countries API </p>
													</div>
												</div>
												<div className='flex lg:hidden ml-4 mt-16 gap-4 lg:absolute  '>
													<a
														href='https://github.com/Boklino/countries-api'
														target='_blank'
													>
														{' '}
														<FiGithub
															size={22}
															color={
																darkMode
																	? 'white'
																	: 'black'
															}
														/>
													</a>

													<a
														target='_blank'
														href='https://api-countriess.netlify.app/'
													>
														<FiExternalLink
															size={22}
															color={
																darkMode
																	? 'white'
																	: 'black'
															}
														/>
													</a>
												</div>
											</p>
										</div>
										<div className=' absolute p-5  left-12 bottom-96 top-60'>
											<div
												className={
													' gap-3 mt-3 opacity-90 hidden lg:flex   ' +
													(darkMode
														? 'text-gray-200 lg:text-gray-300'
														: 'text-black')
												}
											>
												<p>React </p>
												<p>React Router</p>
												<p>Tailwind</p>
												<p>Material UI</p>
												<p>Countries API </p>
											</div>
										</div>
										<div className='hidden lg:flex gap-4 mt-2 absolute p-5 left-52 bottom-72 top-72'>
											<a
												href='https://github.com/Boklino/countries-api'
												target='_blank'
											>
												<FiGithub
													size={22}
													color={
														darkMode
															? 'white'
															: 'black'
													}
												/>{' '}
											</a>
											<a
												target='_blank'
												href='https://api-countriess.netlify.app/'
											>
												<FiExternalLink
													size={22}
													color={
														darkMode
															? 'white'
															: 'black'
													}
												/>
											</a>
										</div>
									</div>
								</div>
							</section>
							<section
								className={
									' mt-56 lg:mt-32 xl:mt-96 lg:p-2 pt-16 lg:pt-2 xl:pt-80 -mr-40 -ml-40 ' +
									(darkMode ? 'bg-gray-900' : 'bg-gray-400')
								}
							>
								<div className=' ml-20  xl:ml-96 '>
									<h1
										className={
											' font-burtons text-3xl mt-8  xl:mt-32  ' +
											(darkMode ? 'text-slate-300 ' : '')
										}
									>
										Contact me
									</h1>
									<form
										className=' lg:min-w-fit inline-block  '
										onSubmit={handleSubmit}
									>
										<div className=' mt-10 '>
											{' '}
											<label
												className={
													' mr-2 ' +
													(darkMode
														? 'text-gray-200'
														: 'text-gray-900')
												}
											>
												Name:
											</label>
											<input
												className={
													' px-3 py-2 rounded-md mr-4 outline-none mt-2 w-full lg:w-fit mb-4  ' +
													(darkMode
														? 'bg-gray-700 text-gray-300'
														: ' bg-gray-300 text-gray-800 placeholder:text-gray-500 ')
												}
												type='text'
												placeholder='name'
												required
												name='name'
											/>
											<br className=' lg:hidden' />
											<label
												className={
													' mr-2 ' +
													(darkMode
														? 'text-gray-200'
														: 'text-gray-900')
												}
											>
												Email:
											</label>
											<input
												className={
													' px-3 py-2 rounded-md outline-none w-full lg:w-fit mt-2 lg:mt-0  ' +
													(darkMode
														? 'bg-gray-700 text-gray-300 '
														: ' bg-gray-300 text-gray-800 placeholder:text-gray-500')
												}
												type='email'
												placeholder='name@email.com'
												required
												name='from_name'
											/>
										</div>
										<div className=' mt-8 '>
											{' '}
											<label
												className={
													' mr-2 ' +
													(darkMode
														? 'text-gray-200'
														: 'text-gray-900')
												}
											>
												Subject:
											</label>
											<input
												placeholder='subject'
												className={
													' mt-2  px-3 py-2 w-full  rounded-md gap-4 outline-none   ' +
													(darkMode
														? 'bg-gray-700 text-gray-300'
														: ' bg-gray-300 text-gray-800 placeholder:text-gray-500')
												}
												type='text'
												required
											/>
										</div>
										<div className=' mt-7 '>
											<label
												className={
													' mr-2 ' +
													(darkMode
														? 'text-gray-200'
														: 'text-gray-900')
												}
											>
												Message:{' '}
											</label>
											<textarea
												className={
													'mt-2 block px-3 py-7 w-full outline-none text-sm  rounded-lg  ' +
													(darkMode
														? ' bg-gray-700 text-gray-300 '
														: ' bg-gray-300 text-gray-800 placeholder:text-gray-500')
												}
												placeholder='Write your Message here...'
												required
												name='message'
											></textarea>
										</div>
										<button
											className={
												'px-4 py-2  rounded-md mt-12 lg:mt-8 mb-10 lg:mb-0 hover:scale-105 ' +
												(darkMode
													? 'text-gray-200 bg-gray-700 '
													: ' text-gray-800 bg-gray-300')
											}
										>
											Send Message
										</button>
									</form>
								</div>
							</section>{' '}
						</div>
					)}
				</div>
			</main>
		</div>
	);
}
